---
- hosts: localhost
  connection: local
  tasks:
    - name: check ssh connection to server
      check_ssh:
        state: 'check_connection'
        ip_address: '192.168.1.13'
        port: 22
      register: result
    - debug: var=result
    - debug: var=result.changed.code
